### ISSUE TITLE
How do i test latest commit locally?

### ISSUE THREAD

**Issue by John4266** [wappalyzer/wappalyzer#5724]
Hello.
I am trying to use the latest commit on my machine and test, but the extension seems to misbehave.

My OS: Windows 10 Pro | 64 Bit
NodeJS version: 16.6.1
Npm version: 8.5.4
Yarn version: 3.1.1
Browser: Firefox Beta 99.0b2 (64-bit)

I first uninstalled the stable version released on the Firefox store,
then i `git clone`ed the `master` branch,
and then i went to `about:debugging#/runtime/this-firefox` and loaded the `manifest.json` file located in `wappalyzer\src\drivers\webextension` using the `Load Temporary Add-on` button.

First of all there's a problem with the extension icon whenever i test it, it appears like this:
![Image](https://i.imgur.com/ptF6djZ.png)
then i wanted to test the following commit: https://github.com/AliasIO/wappalyzer/commit/ef1baa9beb3050e59c069607bdc2155531932b61

I went on `https://book.hacktricks.xyz/` to try, but it only detects 9 technologies, and none of them is `GitBook`.
However, when trying to use the `CLI` version of the tool locally (latest commit), it DOES detect the `GitBook` technology.

UPDATE:
I just tried this whole process on Chrome browser (Version 99.0.4844.51 (Official Build) (64-bit)), and it seems to work there.

How can i test the latest commit on a Firefox Beta browser?

**Comment by AliasIO** [comment]
If it works in Chrome it should work in Firefox too. 🤔 I haven't tried the beta, are you seeing any errors when you inspect the background page?

**Comment by John4266** [comment]
This is a picture of the logs of the extension when accessing `https://book.hacktricks.xyz/about-the-author`
![](https://i.imgur.com/59nZy4D.png)

**Comment by John4266** [comment]
This is a comparison of Chrome `detections` value with Firefox:

<details>
<summary>Chrome</summary>

![](https://i.imgur.com/dQTEpyG.png)
![](https://i.imgur.com/YRvnmob.png)
</details>

<details>
<summary>Firefox</summary>

![](https://i.imgur.com/cwl9Syu.png)
![](https://i.imgur.com/LiMMSpc.png)
</details>

As you can see, Chrome detects 13 technologies while Firefox detects only 11

**Comment by AliasIO** [comment]
I just fixed an issue related to this, try the latest commit.

**Comment by John4266** [comment]
> I just fixed an issue related to this, try the latest commit.

same results.

btw if i am supposed to run any command such as `yarn build`, i get the following error:
![](https://i.imgur.com/NfnBkem.png)

**Comment by John4266** [comment]
I am now encountering new problems when trying to install latest commit in Chrome:
![](https://i.imgur.com/w7hsNeN.png)

**Comment by AliasIO** [comment]
Try running `yarn run link`.

**Comment by John4266** [comment]
> Try running `yarn run link`.

After running `yarn run link`, i tried all the steps again and it seems to work on both browsers, but
On Firefox, it detects 13 technologies, while on Chrome it detects 11 technologies.
And on Firefox, the "invisible icon" error persists.

**Comment by AliasIO** [comment]
I did fix a build issue related to icons, do they show up after running `yarn run build`?

To debug the differences between the browsers, please try clearing the detections cache in both in the extension settings.

**Comment by John4266** [comment]
`yarn run build` throws for me the following errorr:
![](https://i.imgur.com/ZTT8wyS.png)

**Comment by John4266** [comment]
Update: Apparently, when unpacking the `webextension.zip` from a release to a folder, then loading it using the `Load Temporary Add-on...` button, the icon problem is gone.

**Comment by AliasIO** [comment]
Maybe the convert script doesn't work on Windows? Copying just `/src/drivers/webextension/images/icons/converted` from the ZIP file should do the trick.

The header for HTTP/2 is only set in Firefox. I'm not sure why reCAPTCHA isn't reported, did it show up on the page in Chrome?

**Comment by John4266** [comment]
yea the `yarn run convert` doesn't work on windows (at least for me)
![](https://i.imgur.com/ucfVJXc.png)
